name: Build gRPC (Linux)

on:
  workflow_dispatch:

jobs:
  build-grpc-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ninja-build \
            cmake \
            git \
            pkg-config \
            libssl-dev \
            zlib1g-dev

      - name: Build gRPC
        run: |
          git clone -b v1.66.1 --recurse-submodules https://github.com/grpc/grpc
          cmake -S grpc -B grpc/build -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/opt/grpc \
            -DgRPC_SSL_PROVIDER=package \
            -DgRPC_ZLIB_PROVIDER=package \
            -DABSL_PROPAGATE_CXX_STD=ON \
            -DABSL_ENABLE_INSTALL=ON
          cmake --build grpc/build
          sudo cmake --install grpc/build

      - name: Package gRPC
        run: |
          tar -czf grpc-v1.66.1-linux-x64.tar.gz -C /opt/grpc .

      - name: Upload gRPC to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: deps-v1
          files: |
            grpc-v1.66.1-linux-x64.tar.gz